### ISSUE TITLE
Add support for horizontal scrolling mouse wheels

### ISSUE THREAD

**Issue by bitstarr** [armandsalle/butter-slider#11]
I'm using a Logitech MX Master 2 which has a side scrolling wheel. It's very convinient and would be a great improvement, when butter-slider can be scrolled with it.

**Comment by armandsalle** [comment]
Hi @bitstarr ! Thank you for your feedback. It's a good idea, I had this feature in my todo 👌 
how did you hear about Butter Slider?

**Comment by bitstarr** [comment]
@armandsalle i read at codrops about it.
