### ISSUE TITLE
Add support for prev/next buttons

### ISSUE THREAD

**Issue by neilparnold** [armandsalle/butter-slider#12]
Would be great to have something that would move forward/backward by slide or slides.  Useful for keyboard controls too.  
Great slider, nice work!

**Comment by armandsalle** [comment]
hi @neilparnold ! Thank you for your feedback. It's a good idea, but the goal of Butter Slider is to keep it as simple as possible and to manage touch and drag events. There are already a lot of sliders that provide this kind of functionality.

But I could add a method to trigger a scroll, so you can add your own logic, it seems like a good compromise, and maybe an opportunity for plugins! 

how did you hear about Butter Slider?

**Comment by neilparnold** [comment]
Thanks for the reply, makes sense.  You have a getPercentage, so maybe a setPercentage would make sense.  Would let someone create their own navigation systems.  

And I heard about this in the RWD newsletter - [https://responsivedesign.is/articles/rwd-weekly-431/](https://responsivedesign.is/articles/rwd-weekly-431/)

**Comment by trst** [comment]
I realize this has been closed but I'm looking at creating the same behaviour. I'd take a hook for triggering the scroll and write the rest for my use case.

(I 100% respect keeping things simple and appreciate the effort you've made to open-sourcing your work! :tada:)

**Comment by armandsalle** [comment]
Hey @trst ! Thank you for your feedback, I'm currently working on the new version of Butter Slider, but it's not simple for me.
I'm looking for contributors to help me design the new butter slider with hooks system and better performance!

Follow me on Twitter https://twitter.com/ArmandSalle to get the last updates 🍕

**Comment by trst** [comment]
@armandsalle okie dokie! I'm a bit of a dummy when it comes to TS but I suppose if I want new functionality I'm going to have to learn lol. I'll have a go and open up a PR for feedback if I get that far :rofl:

**Comment by armandsalle** [comment]
I learn TS with this project and I'm not sure my TS code is really clean 🤔 If you want to code a big functionality I suggest you to wait for the next version because I will refactor my code almost entirely
